name: Sync Labels

on:
  push:
    branches:
      - master
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v7
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: false
