name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  release:
    name: Generate release with release-please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
